"""empty message

Revision ID: 1b5249df24ad
Revises: None
Create Date: 2014-02-21 06:37:08.999355

"""

# revision identifiers, used by Alembic.
revision = '1b5249df24ad'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
