"""empty message

Revision ID: 25efb286506f
Revises: 2bc042925c8f
Create Date: 2014-02-21 14:21:33.766338

"""

# revision identifiers, used by Alembic.
revision = '25efb286506f'
down_revision = '2bc042925c8f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_2', table_name='user')
    op.drop_index('fb_username_2', table_name='user')
    op.drop_index('username_2', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['fb_username'])
    op.create_unique_constraint(None, 'user', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.drop_constraint(None, 'user')
    op.drop_constraint(None, 'user')
    op.create_index('username_2', 'user', [u'username'], unique=True)
    op.create_index('fb_username_2', 'user', [u'fb_username'], unique=True)
    op.create_index('email_2', 'user', [u'email'], unique=True)
    ### end Alembic commands ###
