"""empty message

Revision ID: e8e7a4b251d
Revises: 1b5249df24ad
Create Date: 2014-02-21 06:40:40.930517

"""

# revision identifiers, used by Alembic.
revision = 'e8e7a4b251d'
down_revision = '1b5249df24ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
